name: Check for invalid dependencies

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  dependency_check_job:
    runs-on: ubuntu-latest
    name: Check for invalid dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: matheusjardimb/dependencies-checker@latest
