name: Check for invalid dependencies

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - feature/**

jobs:
  dependency_check_job:
    runs-on: ubuntu-latest
    name: Check for invalid dependencies
    steps:
      - uses: actions/checkout@v3

      - name: TypeScript Container Action Template
        uses: kevinpollet/typescript-container-action-template@v1

      - name: Check for dependencies without specific version
        uses: matheusjardimb/exact-dependency-checker-action@v0.8.1
